import json

print("Applying FINAL fix: Model is upside down (Y goes to -152). Fixing viewer camera...")

with open('pipeline_new.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Update Cell 4 (Viewer) to handle the inverted Y-axis
for cell in nb['cells']:
    source_str = ''.join(cell.get('source', []))
    if cell['cell_type'] == 'code' and 'webbrowser.open' in source_str:
        print("Updating Viewer Cell with camera fix...")
        cell['source'] = [
            "import os\n",
            "import webbrowser\n",
            "from IPython.display import display, HTML\n",
            "\n",
            "html_template = \"\"\"<!DOCTYPE html>\n",
            "<html>\n",
            "<head>\n",
            "    <title>CityEngine Building Viewer</title>\n",
            "    <meta charset=\\\"utf-8\\\">\n",
            "    <style>\n",
            "        body, html { margin: 0; padding: 0; width: 100%; height: 100%; overflow: hidden; font-family: 'Segoe UI', sans-serif; background: #1a1a2e; }\n",
            "        #viewer-container { width: 100%; height: 100vh; }\n",
            "        #toolbar { position: absolute; top: 15px; left: 15px; z-index: 100; display: flex; flex-direction: column; gap: 8px; }\n",
            "        .btn { background: rgba(0,118,209,0.9); color: white; border: none; padding: 10px 16px; border-radius: 6px; cursor: pointer; font-weight: 600; font-size: 13px; box-shadow: 0 2px 8px rgba(0,0,0,0.3); pointer-events: auto; }\n",
            "        .btn:hover { background: rgba(0,90,161,0.95); }\n",
            "        #status { background: rgba(0,0,0,0.85); color: #0f0; padding: 10px 14px; border-radius: 6px; font-family: 'Consolas', monospace; font-size: 12px; min-width: 280px; border-left: 3px solid #0f0; }\n",
            "    </style>\n",
            "    <link rel=\\\"stylesheet\\\" href=\\\"https://developer.api.autodesk.com/modelderivative/v2/viewers/7.98/style.min.css\\\" type=\\\"text/css\\\">\n",
            "    <script src=\\\"https://developer.api.autodesk.com/modelderivative/v2/viewers/7.98/viewer3D.min.js\\\"></script>\n",
            "    <script src=\\\"https://developer.api.autodesk.com/modelderivative/v2/viewers/7.98/extensions/glTF/glTF.min.js\\\"></script>\n",
            "</head>\n",
            "<body>\n",
            "    <div id='viewer-container'></div>\n",
            "    <div id='toolbar'>\n",
            "        <div id='status'>⏳ Loading Systems...</div>\n",
            "        <button class='btn' onclick='flyToModel()'>🎯 Focus on Building</button>\n",
            "        <button class='btn' style='background:rgba(80,80,80,0.9)' onclick='topView()'>⬆️ Top View</button>\n",
            "        <button class='btn' style='background:rgba(80,80,80,0.9)' onclick='frontView()'>🏠 Front View</button>\n",
            "    </div>\n",
            "\n",
            "    <script>\n",
            "    let viewer;\n",
            "    const log = (m) => document.getElementById('status').innerHTML = m;\n",
            "    \n",
            "    function b64ToBlob(b64) {\n",
            "        const bin = atob(b64);\n",
            "        const buf = new Uint8Array(bin.length);\n",
            "        for (let i = 0; i < bin.length; i++) buf[i] = bin.charCodeAt(i);\n",
            "        return new Blob([buf], {type: 'model/gltf-binary'});\n",
            "    }\n",
            "\n",
            "    function flyToModel() {\n",
            "        if (!viewer) return;\n",
            "        viewer.fitToView(undefined, undefined, true);\n",
            "        log('🎯 Camera focused on building');\n",
            "    }\n",
            "\n",
            "    function topView() {\n",
            "        if (!viewer) return;\n",
            "        // Model goes from Y=-152 to Y=0, so look from above at center Y=-76\n",
            "        viewer.navigation.setPosition(new THREE.Vector3(0, 50, 0));\n",
            "        viewer.navigation.setTarget(new THREE.Vector3(0, -76, 0));\n",
            "        viewer.navigation.setWorldUpVector(new THREE.Vector3(0, 0, -1));\n",
            "        log('⬆️ Top-down view');\n",
            "    }\n",
            "\n",
            "    function frontView() {\n",
            "        if (!viewer) return;\n",
            "        // Look at center of building from front\n",
            "        viewer.navigation.setPosition(new THREE.Vector3(0, -76, 150));\n",
            "        viewer.navigation.setTarget(new THREE.Vector3(0, -76, 0));\n",
            "        viewer.navigation.setWorldUpVector(new THREE.Vector3(0, -1, 0));\n",
            "        log('🏠 Front view');\n",
            "    }\n",
            "\n",
            "    function start() {\n",
            "        if (typeof Autodesk === 'undefined' || typeof Autodesk.Viewing === 'undefined') {\n",
            "            setTimeout(start, 300); return;\n",
            "        }\n",
            "        if (typeof Autodesk.Viewing.Extensions === 'undefined' || typeof Autodesk.Viewing.Extensions.glTF === 'undefined') {\n",
            "            setTimeout(start, 300); return;\n",
            "        }\n",
            "        \n",
            "        log('📡 Initializing Autodesk Viewer...');\n",
            "        \n",
            "        Autodesk.Viewing.Initializer({ env: 'Local' }, function() {\n",
            "            viewer = new Autodesk.Viewing.GuiViewer3D(document.getElementById('viewer-container'));\n",
            "            viewer.start();\n",
            "            viewer.setTheme('dark-theme');\n",
            "            viewer.setEnvMapBackground(true);\n",
            "            viewer.setLightPreset(6);\n",
            "            viewer.setQualityLevel(true, true);\n",
            "            viewer.setGroundShadow(true);\n",
            "            viewer.setGroundReflection(false);\n",
            "            \n",
            "            log('📦 Loading GLB Model...');\n",
            "            const blob = b64ToBlob(\\\"{{MODEL_B64}}\\\");\n",
            "            const url = URL.createObjectURL(blob);\n",
            "            \n",
            "            viewer.loadModel(url + '#.glb', { fileExt: 'glb' }, (model) => {\n",
            "                log('✅ Model Loaded! Adjusting camera...');\n",
            "                \n",
            "                // CRITICAL: The building extends from Y=0 down to Y=-152\n",
            "                // We need to fit the view to see the full extent\n",
            "                setTimeout(() => {\n",
            "                    // First, do a standard fit to view\n",
            "                    viewer.fitToView(undefined, undefined, true);\n",
            "                    \n",
            "                    // Then set a nice isometric camera angle\n",
            "                    setTimeout(() => {\n",
            "                        var bb = viewer.model.getBoundingBox();\n",
            "                        if (bb) {\n",
            "                            var center = bb.getCenter(new THREE.Vector3());\n",
            "                            var size = bb.getSize(new THREE.Vector3());\n",
            "                            var maxDim = Math.max(size.x, size.y, size.z);\n",
            "                            \n",
            "                            // Position camera at isometric angle looking at center\n",
            "                            var camPos = new THREE.Vector3(\n",
            "                                center.x + maxDim * 0.8,\n",
            "                                center.y + maxDim * 0.6,\n",
            "                                center.z + maxDim * 0.8\n",
            "                            );\n",
            "                            \n",
            "                            viewer.navigation.setPosition(camPos);\n",
            "                            viewer.navigation.setTarget(center);\n",
            "                            \n",
            "                            log('✅ <span style=\\\"color:#4caf50\\\">Building Loaded with ' + \n",
            "                                'Bbox: [' + size.x.toFixed(0) + ' x ' + size.y.toFixed(0) + ' x ' + size.z.toFixed(0) + ']</span>');\n",
            "                        }\n",
            "                    }, 500);\n",
            "                }, 1000);\n",
            "            }, (errCode, errMsg) => {\n",
            "                log('❌ Error: Code=' + errCode + ' Msg=' + errMsg);\n",
            "            });\n",
            "        });\n",
            "    }\n",
            "    start();\n",
            "    </script>\n",
            "</body>\n",
            "</html>\n",
            "\"\"\"\n",
            "\n",
            "final_html = html_template.replace(\"{{MODEL_B64}}\", model_b64)\n",
            "html_filename = \"viewer_final.html\"\n",
            "with open(html_filename, \"w\", encoding=\"utf-8\") as f:\n",
            "    f.write(final_html)\n",
            "\n",
            "full_path = os.path.abspath(html_filename)\n",
            "webbrowser.open('file:///' + full_path.replace('\\\\', '/'))\n",
            "\n",
            "display(HTML(f\"\"\"\n",
            "<div style='border: 2px solid #0076d1; background: linear-gradient(135deg, #f0f7ff, #e8f4fd); padding: 25px; border-radius: 12px; font-family: system-ui; text-align: center;'>\n",
            "    <h2 style='color: #0076d1; margin-top: 0;'>🏗️ تم إصلاح الفيوور نهائياً!</h2>\n",
            "    <p style='color: #333;'>المبنى يمتد من Y=0 إلى Y=-152 (مقلوب). تم ضبط الكاميرا تلقائياً.</p>\n",
            "    <div style='display: flex; gap: 10px; justify-content: center; margin-top: 20px;'>\n",
            "        <a href='viewer_final.html' target='_blank' \n",
            "           style='background: #0076d1; color: white; padding: 14px 28px; text-decoration: none; border-radius: 8px; font-weight: bold; box-shadow: 0 4px 12px rgba(0,118,209,0.3);'>\n",
            "           🎮 فتح الفيوور النهائي\n",
            "        </a>\n",
            "    </div>\n",
            "    <p style='color: #888; font-size: 12px; margin-top: 15px;'>استخدم أزرار Focus / Top / Front للتنقل بين أوضاع الكاميرا</p>\n",
            "</div>\n",
            "\"\"\"))\n"
        ]
        break

with open('pipeline_new.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("DONE! Notebook updated with camera fix for inverted Y-axis model.")
