import json

print("Switching to Three.js viewer (much better GLB support)...")

with open('pipeline_new.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

for cell in nb['cells']:
    source_str = ''.join(cell.get('source', []))
    if cell['cell_type'] == 'code' and 'webbrowser.open' in source_str:
        print("Replacing Autodesk Viewer with Three.js viewer...")
        cell['outputs'] = []
        cell['source'] = [
            "import os, webbrowser\n",
            "from IPython.display import display, HTML\n",
            "\n",
            "html_template = \"\"\"<!DOCTYPE html>\n",
            "<html>\n",
            "<head>\n",
            "    <title>CityEngine 3D Building Viewer</title>\n",
            "    <meta charset=\"utf-8\">\n",
            "    <style>\n",
            "        * { margin: 0; padding: 0; box-sizing: border-box; }\n",
            "        body { overflow: hidden; background: #1a1a2e; font-family: 'Segoe UI', sans-serif; }\n",
            "        canvas { display: block; }\n",
            "        #toolbar {\n",
            "            position: absolute; top: 15px; left: 15px; z-index: 10;\n",
            "            display: flex; flex-direction: column; gap: 8px;\n",
            "        }\n",
            "        .btn {\n",
            "            background: rgba(0,118,209,0.9); color: white; border: none;\n",
            "            padding: 10px 18px; border-radius: 6px; cursor: pointer;\n",
            "            font-weight: 600; font-size: 13px;\n",
            "            box-shadow: 0 2px 10px rgba(0,0,0,0.3);\n",
            "        }\n",
            "        .btn:hover { background: rgba(0,90,161,0.95); }\n",
            "        .btn.gray { background: rgba(80,80,80,0.85); }\n",
            "        #status {\n",
            "            background: rgba(0,0,0,0.85); color: #0f0;\n",
            "            padding: 10px 14px; border-radius: 6px;\n",
            "            font-family: Consolas, monospace; font-size: 12px;\n",
            "            min-width: 300px; border-left: 3px solid #0f0;\n",
            "        }\n",
            "        #info {\n",
            "            position: absolute; bottom: 15px; left: 15px; z-index: 10;\n",
            "            background: rgba(0,0,0,0.7); color: #aaa; padding: 8px 14px;\n",
            "            border-radius: 6px; font-size: 11px; font-family: Consolas, monospace;\n",
            "        }\n",
            "    </style>\n",
            "</head>\n",
            "<body>\n",
            "    <div id=\"toolbar\">\n",
            "        <div id=\"status\">⏳ Loading Three.js...</div>\n",
            "        <button class=\"btn\" onclick=\"resetCamera()\">🎯 Focus on Building</button>\n",
            "        <button class=\"btn gray\" onclick=\"toggleWireframe()\">📐 Toggle Wireframe</button>\n",
            "        <button class=\"btn gray\" onclick=\"toggleAutoRotate()\">🔄 Auto Rotate</button>\n",
            "    </div>\n",
            "    <div id=\"info\">Mouse: Left=Rotate | Scroll=Zoom | Right=Pan</div>\n",
            "\n",
            "    <script type=\"importmap\">\n",
            "    {\n",
            "        \"imports\": {\n",
            "            \"three\": \"https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js\",\n",
            "            \"three/addons/\": \"https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/\"\n",
            "        }\n",
            "    }\n",
            "    </script>\n",
            "\n",
            "    <script type=\"module\">\n",
            "    import * as THREE from 'three';\n",
            "    import { OrbitControls } from 'three/addons/controls/OrbitControls.js';\n",
            "    import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';\n",
            "\n",
            "    const log = (m) => document.getElementById('status').innerHTML = m;\n",
            "    let wireframeMode = false;\n",
            "    let loadedModel = null;\n",
            "\n",
            "    // Scene setup\n",
            "    const scene = new THREE.Scene();\n",
            "    scene.background = new THREE.Color(0x87CEEB); // Sky blue\n",
            "    scene.fog = new THREE.Fog(0x87CEEB, 500, 2000);\n",
            "\n",
            "    // Camera\n",
            "    const camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 0.1, 5000);\n",
            "    camera.position.set(150, 200, 250);\n",
            "\n",
            "    // Renderer\n",
            "    const renderer = new THREE.WebGLRenderer({ antialias: true });\n",
            "    renderer.setSize(window.innerWidth, window.innerHeight);\n",
            "    renderer.setPixelRatio(window.devicePixelRatio);\n",
            "    renderer.shadowMap.enabled = true;\n",
            "    renderer.shadowMap.type = THREE.PCFSoftShadowMap;\n",
            "    renderer.toneMapping = THREE.ACESFilmicToneMapping;\n",
            "    renderer.toneMappingExposure = 1.2;\n",
            "    document.body.appendChild(renderer.domElement);\n",
            "\n",
            "    // Controls\n",
            "    const controls = new OrbitControls(camera, renderer.domElement);\n",
            "    controls.enableDamping = true;\n",
            "    controls.dampingFactor = 0.05;\n",
            "    controls.target.set(0, -76, 0);\n",
            "\n",
            "    // Lighting\n",
            "    const ambientLight = new THREE.AmbientLight(0xffffff, 0.6);\n",
            "    scene.add(ambientLight);\n",
            "\n",
            "    const dirLight = new THREE.DirectionalLight(0xffffff, 1.2);\n",
            "    dirLight.position.set(100, 200, 100);\n",
            "    dirLight.castShadow = true;\n",
            "    dirLight.shadow.mapSize.width = 2048;\n",
            "    dirLight.shadow.mapSize.height = 2048;\n",
            "    dirLight.shadow.camera.near = 0.5;\n",
            "    dirLight.shadow.camera.far = 1000;\n",
            "    dirLight.shadow.camera.left = -200;\n",
            "    dirLight.shadow.camera.right = 200;\n",
            "    dirLight.shadow.camera.top = 200;\n",
            "    dirLight.shadow.camera.bottom = -200;\n",
            "    scene.add(dirLight);\n",
            "\n",
            "    const hemiLight = new THREE.HemisphereLight(0x87CEEB, 0x362D1B, 0.5);\n",
            "    scene.add(hemiLight);\n",
            "\n",
            "    // Ground plane\n",
            "    const groundGeo = new THREE.PlaneGeometry(2000, 2000);\n",
            "    const groundMat = new THREE.MeshStandardMaterial({ color: 0x4a7c59, roughness: 0.9 });\n",
            "    const ground = new THREE.Mesh(groundGeo, groundMat);\n",
            "    ground.rotation.x = -Math.PI / 2;\n",
            "    ground.receiveShadow = true;\n",
            "    scene.add(ground);\n",
            "\n",
            "    // Grid helper\n",
            "    const gridHelper = new THREE.GridHelper(500, 50, 0x888888, 0x444444);\n",
            "    gridHelper.position.y = 0.1;\n",
            "    scene.add(gridHelper);\n",
            "\n",
            "    // Axes helper\n",
            "    const axesHelper = new THREE.AxesHelper(50);\n",
            "    scene.add(axesHelper);\n",
            "\n",
            "    // Load GLB model\n",
            "    log('📦 Decoding Base64 model data...');\n",
            "    const b64 = \"{{MODEL_B64}}\";\n",
            "    const binStr = atob(b64);\n",
            "    const bytes = new Uint8Array(binStr.length);\n",
            "    for (let i = 0; i < binStr.length; i++) bytes[i] = binStr.charCodeAt(i);\n",
            "    const blob = new Blob([bytes.buffer], { type: 'model/gltf-binary' });\n",
            "    const url = URL.createObjectURL(blob);\n",
            "\n",
            "    log('🔧 Loading GLB with Three.js GLTFLoader...');\n",
            "    const loader = new GLTFLoader();\n",
            "    loader.load(url, (gltf) => {\n",
            "        loadedModel = gltf.scene;\n",
            "        \n",
            "        // Enable shadows on all meshes\n",
            "        loadedModel.traverse((child) => {\n",
            "            if (child.isMesh) {\n",
            "                child.castShadow = true;\n",
            "                child.receiveShadow = true;\n",
            "                if (child.material) {\n",
            "                    child.material.side = THREE.DoubleSide;\n",
            "                }\n",
            "            }\n",
            "        });\n",
            "        \n",
            "        scene.add(loadedModel);\n",
            "        \n",
            "        // Calculate bounding box for camera positioning\n",
            "        const box = new THREE.Box3().setFromObject(loadedModel);\n",
            "        const center = box.getCenter(new THREE.Vector3());\n",
            "        const size = box.getSize(new THREE.Vector3());\n",
            "        const maxDim = Math.max(size.x, size.y, size.z);\n",
            "        \n",
            "        // Position camera for nice isometric view\n",
            "        camera.position.set(\n",
            "            center.x + maxDim * 1.0,\n",
            "            center.y + maxDim * 0.8,\n",
            "            center.z + maxDim * 1.0\n",
            "        );\n",
            "        controls.target.copy(center);\n",
            "        controls.update();\n",
            "        \n",
            "        // Adjust ground to bottom of building\n",
            "        ground.position.y = box.min.y;\n",
            "        gridHelper.position.y = box.min.y + 0.1;\n",
            "        \n",
            "        log('✅ <span style=\"color:#4caf50\">Building Loaded!</span> ' +\n",
            "            'Size: ' + size.x.toFixed(0) + 'x' + size.y.toFixed(0) + 'x' + size.z.toFixed(0) + 'm');\n",
            "        \n",
            "        URL.revokeObjectURL(url);\n",
            "    }, (progress) => {\n",
            "        if (progress.total > 0) {\n",
            "            const pct = Math.round(progress.loaded / progress.total * 100);\n",
            "            log('📦 Loading... ' + pct + '%');\n",
            "        }\n",
            "    }, (error) => {\n",
            "        log('❌ Error: ' + error.message);\n",
            "        console.error(error);\n",
            "    });\n",
            "\n",
            "    // Window resize\n",
            "    window.addEventListener('resize', () => {\n",
            "        camera.aspect = window.innerWidth / window.innerHeight;\n",
            "        camera.updateProjectionMatrix();\n",
            "        renderer.setSize(window.innerWidth, window.innerHeight);\n",
            "    });\n",
            "\n",
            "    // Animation loop\n",
            "    function animate() {\n",
            "        requestAnimationFrame(animate);\n",
            "        controls.update();\n",
            "        renderer.render(scene, camera);\n",
            "    }\n",
            "    animate();\n",
            "\n",
            "    // Global functions for buttons\n",
            "    window.resetCamera = () => {\n",
            "        if (!loadedModel) return;\n",
            "        const box = new THREE.Box3().setFromObject(loadedModel);\n",
            "        const center = box.getCenter(new THREE.Vector3());\n",
            "        const size = box.getSize(new THREE.Vector3());\n",
            "        const maxDim = Math.max(size.x, size.y, size.z);\n",
            "        camera.position.set(center.x + maxDim, center.y + maxDim * 0.7, center.z + maxDim);\n",
            "        controls.target.copy(center);\n",
            "        controls.update();\n",
            "        log('🎯 Camera focused on building');\n",
            "    };\n",
            "\n",
            "    window.toggleWireframe = () => {\n",
            "        wireframeMode = !wireframeMode;\n",
            "        if (loadedModel) {\n",
            "            loadedModel.traverse((child) => {\n",
            "                if (child.isMesh && child.material) {\n",
            "                    child.material.wireframe = wireframeMode;\n",
            "                }\n",
            "            });\n",
            "        }\n",
            "        log(wireframeMode ? '📐 Wireframe ON' : '📐 Wireframe OFF');\n",
            "    };\n",
            "\n",
            "    window.toggleAutoRotate = () => {\n",
            "        controls.autoRotate = !controls.autoRotate;\n",
            "        controls.autoRotateSpeed = 2.0;\n",
            "        log(controls.autoRotate ? '🔄 Auto-rotate ON' : '🔄 Auto-rotate OFF');\n",
            "    };\n",
            "    </script>\n",
            "</body>\n",
            "</html>\n",
            "\"\"\"\n",
            "\n",
            "final_html = html_template.replace('{{MODEL_B64}}', model_b64)\n",
            "html_filename = 'viewer_threejs.html'\n",
            "with open(html_filename, 'w', encoding='utf-8') as f:\n",
            "    f.write(final_html)\n",
            "\n",
            "full_path = os.path.abspath(html_filename)\n",
            "webbrowser.open('file:///' + full_path.replace(chr(92), '/'))\n",
            "\n",
            "display(HTML(\"\"\"\n",
            "<div style='border: 2px solid #28a745; background: linear-gradient(135deg, #f0fff4, #e8f5e9); padding: 25px; border-radius: 12px; font-family: system-ui; text-align: center;'>\n",
            "    <h2 style='color: #28a745; margin-top: 0;'>🎉 فيوور Three.js الجديد جاهز!</h2>\n",
            "    <p style='color: #333;'>تم استبدال Autodesk Viewer بـ <b>Three.js GLTFLoader</b> لضمان عرض المبنى بشكل صحيح.</p>\n",
            "    <ul style='text-align: right; color: #555; max-width: 400px; margin: 15px auto;'>\n",
            "        <li>عرض المبنى مع الإضاءة والظلال</li>\n",
            "        <li>أرضية خضراء وشبكة إحداثيات</li>\n",
            "        <li>دوران تلقائي وعرض Wireframe</li>\n",
            "    </ul>\n",
            "    <a href='viewer_threejs.html' target='_blank' \n",
            "       style='background: #28a745; color: white; padding: 14px 28px; text-decoration: none; border-radius: 8px; font-weight: bold; display: inline-block; box-shadow: 0 4px 12px rgba(40,167,69,0.3);'>\n",
            "       🏗️ فتح الفيوور ثلاثي الأبعاد\n",
            "    </a>\n",
            "</div>\n",
            "\"\"\"))\n"
        ]
        break

with open('pipeline_new.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("DONE! Notebook updated with Three.js viewer.")
