import json
import os

print("Updating notebook with 'Fly to' button and axis helpers...")

with open('pipeline_new.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# 1. Update Cell 4 (Enhanced Viewer with Fly To & Debug Tools)
found_cell = False
for cell in nb['cells']:
    source_str = ''.join(cell.get('source', []))
    if cell['cell_type'] == 'code' and 'webbrowser.open' in source_str:
        print("Updating Viewer Cell...")
        cell['source'] = [
            "import os\n",
            "import webbrowser\n",
            "from IPython.display import display, HTML\n",
            "\n",
            "# كود الـ HTML المطور مع زر 'Fly to' وأدوات تصحيح إضافية\n",
            "html_template = \"\"\"<!DOCTYPE html>\n",
            "<html>\n",
            "<head>\n",
            "    <title>CityEngine Pro Viewer + Fly To</title>\n",
            "    <meta charset=\\\"utf-8\\\">\n",
            "    <style>\n",
            "        body, html { margin: 0; padding: 0; width: 100%; height: 100%; overflow: hidden; font-family: sans-serif; background: #1a1a1a; }\n",
            "        #viewer-v15 { width: 100%; height: 100vh; }\n",
            "        #toolbar { position: absolute; top: 20px; left: 20px; z-index: 100; display: flex; flex-direction: column; gap: 10px; }\n",
            "        .btn { \n",
            "            background: #0076d1; color: white; border: none; padding: 12px 20px; \n",
            "            border-radius: 6px; cursor: pointer; font-weight: bold; font-size: 14px;\n",
            "            box-shadow: 0 4px 6px rgba(0,0,0,0.3); transition: all 0.2s;\n",
            "            pointer-events: auto;\n",
            "        }\n",
            "        .btn:hover { background: #00569d; transform: translateY(-2px); }\n",
            "        .btn.secondary { background: #444; }\n",
            "        #status { background: rgba(0,0,0,0.8); color: #0f0; padding: 10px; border-radius: 5px; font-family: monospace; font-size: 12px; pointer-events: none; min-width: 250px; }\n",
            "    </style>\n",
            "    <link rel=\"stylesheet\" href=\"https://developer.api.autodesk.com/modelderivative/v2/viewers/7.98/style.min.css\" type=\"text/css\">\n",
            "    <script src=\"https://developer.api.autodesk.com/modelderivative/v2/viewers/7.98/viewer3D.min.js\"></script>\n",
            "    <script src=\"https://developer.api.autodesk.com/modelderivative/v2/viewers/7.98/extensions/glTF/glTF.min.js\"></script>\n",
            "</head>\n",
            "<body>\n",
            "    <div id='viewer-v15'></div>\n",
            "    <div id='toolbar'>\n",
            "        <div id='status'>System Ready...</div>\n",
            "        <button class='btn' onclick='flyToModel()'>🚀 Fly to Model (Focus)</button>\n",
            "        <button class='btn secondary' onclick='toggleAxes()'>📐 Toggle Axes Helper</button>\n",
            "        <button class='btn secondary' onclick='resetView()'>🏠 Home View</button>\n",
            "    </div>\n",
            "\n",
            "    <script>\n",
            "    let viewer;\n",
            "    let axesHelper = null;\n",
            "\n",
            "    const log = (m) => document.getElementById('status').innerText = '> ' + m;\n",
            "    \n",
            "    function b64ToBlob(b64) {\n",
            "        const bin = atob(b64);\n",
            "        const buf = new Uint8Array(bin.length);\n",
            "        for (let i = 0; i < bin.length; i++) buf[i] = bin.charCodeAt(i);\n",
            "        return new Blob([buf], {type: 'model/gltf-binary'});\n",
            "    }\n",
            "\n",
            "    function flyToModel() {\n",
            "        if (viewer) {\n",
            "            viewer.fitToView();\n",
            "            log('Flew to Model Bounding Box');\n",
            "        }\n",
            "    }\n",
            "\n",
            "    function resetView() {\n",
            "        if (viewer) viewer.navigation.toDefaultView();\n",
            "    }\n",
            "\n",
            "    function toggleAxes() {\n",
            "        if (!viewer) return;\n",
            "        if (!axesHelper) {\n",
            "            axesHelper = new THREE.AxesHelper(50);\n",
            "            viewer.impl.scene.add(axesHelper);\n",
            "            log('Axes Helper Enabled');\n",
            "        } else {\n",
            "            viewer.impl.scene.remove(axesHelper);\n",
            "            axesHelper = null;\n",
            "            log('Axes Helper Disabled');\n",
            "        }\n",
            "        viewer.impl.invalidate(true);\n",
            "    }\n",
            "\n",
            "    function start() {\n",
            "        if (typeof Autodesk === 'undefined' || typeof Autodesk.Viewing.Extensions.glTF === 'undefined') {\n",
            "            setTimeout(start, 500); return;\n",
            "        }\n",
            "        \n",
            "        Autodesk.Viewing.Initializer({ env: 'Local' }, function() {\n",
            "            viewer = new Autodesk.Viewing.GuiViewer3D(document.getElementById('viewer-v15'));\n",
            "            viewer.start();\n",
            "            \n",
            "            viewer.setTheme('dark-theme');\n",
            "            viewer.setEnvMapBackground(true);\n",
            "            viewer.setLightPreset(1);\n",
            "            viewer.setQualityLevel(true, true);\n",
            "            \n",
            "            const url = URL.createObjectURL(b64ToBlob(\"{{MODEL_B64}}\"));\n",
            "            log('Loading GLB into memory...');\n",
            "            \n",
            "            viewer.loadModel(url + '#.glb', { fileExt: 'glb' }, (model) => {\n",
            "                log('Model Loaded! Calculating bounds...');\n",
            "                setTimeout(() => {\n",
            "                    viewer.fitToView();\n",
            "                    log('Success: Model In View!');\n",
            "                    // Show axes by default to see where things are\n",
            "                    toggleAxes();\n",
            "                }, 1000);\n",
            "            }, (err) => {\n",
            "                log('Error: ' + err);\n",
            "            });\n",
            "        });\n",
            "    }\n",
            "    start();\n",
            "    </script>\n",
            "</body>\n",
            "</html>\n",
            "\"\"\"\n",
            "\n",
            "final_html = html_template.replace(\"{{MODEL_B64}}\", model_b64)\n",
            "html_filename = \"viewer_pro.html\"\n",
            "with open(html_filename, \"w\", encoding=\"utf-8\") as f:\n",
            "    f.write(final_html)\n",
            "\n",
            "full_path = os.path.abspath(html_filename)\n",
            "webbrowser.open('file:///' + full_path.replace('\\\\', '/'))\n",
            "\n",
            "display(HTML(f\"\"\"\n",
            "<div style='border: 2px solid #0076d1; background: #fff; padding: 20px; border-radius: 10px; font-family: system-ui;'>\n",
            "    <h3 style='color: #0076d1; margin-top: 0;'>🎮 الفيوور المطور جاهز!</h3>\n",
            "    <p>لقد أضفنا زر <b>🚀 Fly to Model</b> داخل الصفحة الجديدة لمساعدتك في العثور على المبنى فوراً.</p>\n",
            "    <div style='margin-top: 15px;'>\n",
            "        <a href='viewer_pro.html' target='_blank' \n",
            "           style='background: #0076d1; color: white; padding: 12px 25px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block;'>\n",
            "           🔗 فتح الفيوور المطور (Fly To)\n",
            "        </a>\n",
            "    </div>\n",
            "</div>\n",
            "\"\"\"))\n"
        ]
        found_cell = True
        break

if found_cell:
    with open('pipeline_new.ipynb', 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    print("Notebook updated successfully!")
else:
    print("Error: Targeted cell not found.")
